const MasterData = [
    {type1: 'FIP', type2: 'Cap', size1: '1/8"', size2: '1/8"', wall: '1', column: 'A', row: '1',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Cap', size1: '1/4"', size2: '1/4"', wall: '1', column: 'B', row: '1',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Cap', size1: '3/8"', size2: '3/8"', wall: '1', column: 'C', row: '1',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Cap', size1: '1/2"', size2: '1/2"', wall: '1', column: 'D', row: '1',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Cap', size1: '3/4"', size2: '3/4"', wall: '1', column: 'E', row: '1',  secondSize: false,}, 
    {type1: 'FIP', type2: 'FIP', size1: '1/8"', size2: '1/8"', wall: '1', column: 'F', row: '1',  secondSize: true,}, 
    {type1: 'MIP', type2: 'HEX Head Plug', size1: '1/8"', size2: '1/8"', wall: '1', column: 'A', row: '2',  secondSize: false,}, 
    {type1: 'MIP', type2: 'HEX Head Plug', size1: '1/4"', size2: '1/4"', wall: '1', column: 'B', row: '2',  secondSize: false,}, 
    {type1: 'MIP', type2: 'HEX Head Plug', size1: '3/8"', size2: '3/8"', wall: '1', column: 'C', row: '2',  secondSize: false,}, 
    {type1: 'MIP', type2: 'SQR Head Plug', size1: '1/8"', size2: '1/8"', wall: '1', column: 'D', row: '2',  secondSize: false,}, 
    {type1: 'MIP', type2: 'HEX Head Plug', size1: '1/2"', size2: '1/2"', wall: '1', column: 'E', row: '2',  secondSize: false,}, 
    {type1: 'MIP', type2: 'SQR Head Plug', size1: '1/4"', size2: '1/4"', wall: '1', column: 'F', row: '2',  secondSize: false,}, 
    {type1: 'MIP', type2: 'SQR Head Plug', size1: '3/8"', size2: '3/8"', wall: '1', column: 'A', row: '3',  secondSize: false,}, 
    {type1: 'MIP', type2: 'SQR Head Plug', size1: '1/2"', size2: '1/2"', wall: '1', column: 'B', row: '3',  secondSize: false,}, 
    {type1: 'MIP', type2: 'SQR Head Plug', size1: '3/4"', size2: '3/4"', wall: '1', column: 'C', row: '3',  secondSize: false,}, 
    {type1: 'MIP', type2: 'Ctr Sunk Plug', size1: '1/8"', size2: '1/8"', wall: '1', column: 'D', row: '3',  secondSize: false,}, 
    {type1: 'MIP', type2: 'Ctr Sunk Plug', size1: '1/4"', size2: '1/4"', wall: '1', column: 'E', row: '3',  secondSize: false,}, 
    {type1: 'MIP', type2: 'Ctr Sunk Plug', size1: '3/8"', size2: '3/8"', wall: '1', column: 'F', row: '3',  secondSize: false,}, 
    {type1: 'MIP', type2: 'Ctr Sunk Plug', size1: '1/2"', size2: '1/2"', wall: '1', column: 'A', row: '4',  secondSize: false,}, 
    {type1: 'MIP', type2: 'Ctr Sunk Plug', size1: '3/4"', size2: '3/4"', wall: '1', column: 'B', row: '4',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Tee', size1: '1/8" x 1/8" x 1/8"', size2: '1/8" x 1/8" x 1/8"', wall: '1', column: 'C', row: '4',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Tee', size1: '1/4" x 1/4" x 1/4"', size2: '1/4" x 1/4" x 1/4"', wall: '1', column: 'D', row: '4',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Tee', size1: '3/8" x 3/8" x 3/8"', size2: '3/8" x 3/8" x 3/8"', wall: '1', column: 'E', row: '4',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Tee', size1: '1/2" x 1/2" x 1/2"', size2: '1/2" x 1/2" x 1/2"', wall: '1', column: 'F', row: '4',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Tee', size1: '3/4" x 3/4" x 3/4"', size2: '3/4" x 3/4" x 3/4"', wall: '1', column: 'A', row: '5',  secondSize: false,}, 
    {type1: 'FIP', type2: 'MIP', size1: '1/4"', size2: '1/8"', wall: '1', column: 'B', row: '5',  secondSize: true,}, 
    {type1: 'FIP', type2: 'MIP', size1: '3/8"', size2: '1/4"', wall: '1', column: 'C', row: '5',  secondSize: true,}, 
    {type1: 'MIP', type2: 'HEX Nipple', size1: '1/8"', size2: '1/8"', wall: '1', column: 'D', row: '5',  secondSize: true,}, 
    {type1: 'MIP', type2: 'HEX Nipple', size1: '1/4"', size2: '1/4"', wall: '1', column: 'E', row: '5',  secondSize: true,}, 
    {type1: 'MIP', type2: 'HEX Nipple', size1: '3/8"', size2: '3/8"', wall: '1', column: 'F', row: '5',  secondSize: true,}, 
    {type1: 'MIP', type2: 'HEX Nipple', size1: '1/2"', size2: '3/8"', wall: '1', column: 'A', row: '6',  secondSize: true,}, 
    {type1: 'MIP', type2: 'HEX Nipple', size1: '1/2"', size2: '1/2"', wall: '1', column: 'B', row: '6',  secondSize: true,}, 
    {type1: 'MIP', type2: 'HEX Nipple', size1: '3/4"', size2: '3/4"', wall: '1', column: 'C', row: '6',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/8"', size2: 'Close', wall: '1', column: 'D', row: '6',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/8"', size2: '1-1/2"', wall: '1', column: 'E', row: '6',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/8"', size2: '2"', wall: '1', column: 'F', row: '6',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/8"', size2: '3"', wall: '1', column: 'A', row: '7',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/4"', size2: 'Close', wall: '1', column: 'B', row: '7',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/4"', size2: '1-1/2"', wall: '1', column: 'C', row: '7',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/4"', size2: '2"', wall: '1', column: 'D', row: '7',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/4"', size2: '2-1/2"', wall: '1', column: 'E', row: '7',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/4"', size2: '3"', wall: '1', column: 'F', row: '7',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/4"', size2: '4"', wall: '1', column: 'A', row: '8',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/4"', size2: '5"', wall: '1', column: 'B', row: '8',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '3/8"', size2: 'Close', wall: '1', column: 'C', row: '8',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '3/8"', size2: '1-1/2"', wall: '1', column: 'D', row: '8',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '3/8"', size2: '2"', wall: '1', column: 'E', row: '8',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '3/8"', size2: '2-1/2"', wall: '1', column: 'A', row: '9',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '3/8"', size2: '3"', wall: '1', column: 'B', row: '9',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '3/8"', size2: '4"', wall: '1', column: 'C', row: '9',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/2"', size2: 'Close', wall: '1', column: 'D', row: '9',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/2"', size2: '1-1/2"', wall: '1', column: 'E', row: '9',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/2"', size2: '2"', wall: '1', column: 'A', row: '10',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/2"', size2: '2-1/2"', wall: '1', column: 'B', row: '10',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/2"', size2: '3"', wall: '1', column: 'C', row: '10',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/2"', size2: '4"', wall: '1', column: 'D', row: '10',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/2"', size2: '5"', wall: '1', column: 'E', row: '10',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '1/2"', size2: '6"', wall: '1', column: 'A', row: '11',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '3/4"', size2: 'Close', wall: '1', column: 'B', row: '11',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '3/4"', size2: '1-1/2"', wall: '1', column: 'C', row: '11',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '3/4"', size2: '2"', wall: '1', column: 'D', row: '11',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '3/4"', size2: '2-1/2"', wall: '1', column: 'E', row: '11',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '3/4"', size2: '3"', wall: '1', column: 'A', row: '12',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '3/4"', size2: '3-1/2"', wall: '1', column: 'B', row: '12',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '3/4"', size2: '4"', wall: '1', column: 'C', row: '12',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '3/4"', size2: '5"', wall: '1', column: 'D', row: '12',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Nipple', size1: '3/4"', size2: '6"', wall: '1', column: 'E', row: '12',  secondSize: true,}, 
    {type1: 'FIP', type2: 'FIP', size1: '1/2"', size2: '1/2"', wall: '2', column: 'A', row: '1',  secondSize: true,}, 
    {type1: 'FIP', type2: 'FIP', size1: '3/8"', size2: '3/8"', wall: '2', column: 'B', row: '1',  secondSize: true,}, 
    {type1: 'FIP', type2: 'FIP', size1: '1/4"', size2: '1/4"', wall: '2', column: 'C', row: '1',  secondSize: true,}, 
    {type1: 'FIP', type2: 'FIP', size1: '3/4"', size2: '3/4"', wall: '2', column: 'D', row: '1',  secondSize: true,}, 
    {type1: 'FIP', type2: 'FIP', size1: '1/4"', size2: '1/8"', wall: '2', column: 'E', row: '1',  secondSize: true,}, 
    {type1: 'FIP', type2: 'FIP', size1: '3/8"', size2: '1/4"', wall: '2', column: 'F', row: '1',  secondSize: true,}, 
    {type1: 'FIP', type2: 'FIP', size1: '1/2"', size2: '1/4"', wall: '2', column: 'A', row: '2',  secondSize: true,}, 
    {type1: 'FIP', type2: 'FIP', size1: '1/2"', size2: '3/8"', wall: '2', column: 'B', row: '2',  secondSize: true,}, 
    {type1: 'FIP', type2: 'FIP', size1: '3/4"', size2: '1/2"', wall: '2', column: 'C', row: '2',  secondSize: true,}, 
    {type1: 'FIP', type2: 'Elbow', size1: '1/8"', size2: '1/8"', wall: '2', column: 'D', row: '2',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Elbow', size1: '1/4"', size2: '1/4"', wall: '2', column: 'E', row: '2',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Elbow', size1: '3/8"', size2: '3/8"', wall: '2', column: 'F', row: '2',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Elbow', size1: '1/2"', size2: '1/2"', wall: '2', column: 'A', row: '3',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Elbow', size1: '3/4"', size2: '3/4"', wall: '2', column: 'B', row: '3',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Street Elbow', size1: '1/8"', size2: '1/8"', wall: '2', column: 'C', row: '3',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Street Elbow', size1: '1/4"', size2: '1/4"', wall: '2', column: 'D', row: '3',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Street Elbow', size1: '3/8"', size2: '3/8"', wall: '2', column: 'E', row: '3',  secondSize: false,}, 
    {type1: 'FIP', type2: 'Street Elbow', size1: '1/2"', size2: '1/2"', wall: '2', column: 'F', row: '3',  secondSize: false,}, 
    {type1: 'MIP', type2: 'HEX Bushing', size1: '1/4"', size2: '1/8"', wall: '2', column: 'A', row: '4',  secondSize: true,}, 
    {type1: 'MIP', type2: 'HEX Bushing', size1: '3/8"', size2: '1/8"', wall: '2', column: 'B', row: '4',  secondSize: true,}, 
    {type1: 'MIP', type2: 'HEX Bushing', size1: '3/8"', size2: '1/4"', wall: '2', column: 'C', row: '4',  secondSize: true,}, 
    {type1: 'MIP', type2: 'HEX Bushing', size1: '1/2"', size2: '1/8"', wall: '2', column: 'D', row: '4',  secondSize: true,}, 
    {type1: 'MIP', type2: 'HEX Bushing', size1: '1/2"', size2: '1/4"', wall: '2', column: 'E', row: '4',  secondSize: true,}, 
    {type1: 'MIP', type2: 'HEX Bushing', size1: '1/2"', size2: '3/8"', wall: '2', column: 'F', row: '4',  secondSize: true,}, 
    {type1: 'MIP', type2: 'HEX Bushing', size1: '3/4"', size2: '1/8"', wall: '2', column: 'A', row: '5',  secondSize: true,}, 
    {type1: 'MIP', type2: 'HEX Bushing', size1: '3/4"', size2: '1/4"', wall: '2', column: 'B', row: '5',  secondSize: true,}, 
    {type1: 'MIP', type2: 'HEX Bushing', size1: '3/4"', size2: '3/8"', wall: '2', column: 'C', row: '5',  secondSize: true,}, 
    {type1: 'MIP', type2: 'HEX Bushing', size1: '3/4"', size2: '1/2"', wall: '2', column: 'D', row: '5',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Face Bushing', size1: '1/2"', size2: '3/8"', wall: '2', column: 'E', row: '5',  secondSize: true,}, 
    {type1: 'MIP', type2: 'Face Bushing', size1: '3/4"', size2: '1/2"', wall: '2', column: 'F', row: '5',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'MIP', size1: '1/8"', size2: '1/8"', wall: '2', column: 'A', row: '6',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'MIP', size1: '3/16"', size2: '1/8"', wall: '2', column: 'B', row: '6',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'MIP', size1: '1/4"', size2: '1/8"', wall: '2', column: 'C', row: '6',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'FIP', size1: '1/4"', size2: '1/8"', wall: '2', column: 'D', row: '6',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'MIP', size1: '1/4"', size2: '1/4"', wall: '2', column: 'E', row: '6',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'FIP', size1: '1/4"', size2: '1/4"', wall: '2', column: 'F', row: '6',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'MIP', size1: '5/16"', size2: '1/8"', wall: '2', column: 'A', row: '7',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'MIP', size1: '5/16"', size2: '1/4"', wall: '2', column: 'B', row: '7',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'MIP', size1: '3/8"', size2: '1/8"', wall: '2', column: 'C', row: '7',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'MIP', size1: '3/8"', size2: '1/4"', wall: '2', column: 'D', row: '7',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'FIP', size1: '3/8"', size2: '1/4"', wall: '2', column: 'E', row: '7',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'MIP', size1: '3/8"', size2: '3/8"', wall: '2', column: 'F', row: '7',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'Swivel Adapter', size1: '3/8"', size2: '3/8"', wall: '2', column: 'A', row: '8',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'MIP', size1: '3/8"', size2: '1/2"', wall: '2', column: 'B', row: '8',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'FIP', size1: '3/8"', size2: '1/2"', wall: '2', column: 'C', row: '8',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'MIP', size1: '1/2"', size2: '3/8"', wall: '2', column: 'D', row: '8',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'MIP', size1: '1/2"', size2: '1/2"', wall: '2', column: 'E', row: '8',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'FIP', size1: '1/2"', size2: '1/2"', wall: '2', column: 'F', row: '8',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'MIP', size1: '5/8"', size2: '1/2"', wall: '2', column: 'A', row: '9',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'MIP', size1: '3/4"', size2: '3/4"', wall: '2', column: 'B', row: '9',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'Male Elbow', size1: '1/4"', size2: '1/8"', wall: '2', column: 'C', row: '9',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'Male Elbow', size1: '5/16"', size2: '1/4"', wall: '2', column: 'D', row: '9',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'Male Elbow', size1: '3/8"', size2: '1/8"', wall: '2', column: 'E', row: '9',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'Male Elbow', size1: '3/8"', size2: '1/4"', wall: '2', column: 'F', row: '9',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'Coupling', size1: '3/16"', size2: '3/16"', wall: '2', column: 'A', row: '10',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'Coupling', size1: '1/4"', size2: '1/4"', wall: '2', column: 'B', row: '10',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'Coupling', size1: '5/16"', size2: '5/16"', wall: '2', column: 'C', row: '10',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'Coupling', size1: '3/8"', size2: '3/8"', wall: '2', column: 'D', row: '10',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'Coupling', size1: '1/2"', size2: '1/2"', wall: '2', column: 'E', row: '10',  secondSize: true,}, 
    {type1: 'Hose Barb', type2: 'Tee', size1: '1/4" x 1/4" x 1/4"', size2: '1/4" x 1/4" x 1/4"', wall: '2', column: 'F', row: '10',  secondSize: false,}, 
    {type1: 'Hose Barb', type2: 'Tee', size1: '3/8" x 3/8" x 3/8"', size2: '3/8" x 3/8" x 3/8"', wall: '2', column: 'A', row: '11',  secondSize: false,}, 
    {type1: 'MHT', type2: 'FIP', size1: '3/4"', size2: '1/2"', wall: '2', column: 'B', row: '11',  secondSize: true,}, 
    {type1: 'MHT', type2: 'FIP', size1: '3/4"', size2: '3/4"', wall: '2', column: 'C', row: '11',  secondSize: true,}, 
    {type1: 'FHT', type2: 'Swivel Union', size1: '3/4"', size2: '3/4"', wall: '2', column: 'D', row: '11',  secondSize: true,}, 
    {type1: 'FHT', type2: 'MIP', size1: '3/4"', size2: '1/2"', wall: '2', column: 'E', row: '11',  secondSize: true,}, 
    {type1: 'FHT', type2: 'MIP', size1: '3/4"', size2: '3/4"', wall: '2', column: 'F', row: '11',  secondSize: true,}, 
    {type1: 'FHT', type2: 'FIP', size1: '3/4"', size2: '1/2"', wall: '2', column: 'A', row: '12',  secondSize: true,}, 
    {type1: 'FHT', type2: 'FIP', size1: '3/4"', size2: '3/4"', wall: '2', column: 'B', row: '12',  secondSize: true,}, 
    {type1: 'MHT', type2: 'MIP', size1: '3/4"', size2: '1/2"', wall: '2', column: 'C', row: '12',  secondSize: true,}, 
    {type1: 'MHT', type2: 'MIP', size1: '3/4"', size2: '3/4"', wall: '2', column: 'D', row: '12',  secondSize: true,}, 
    {type1: 'MHT', type2: 'MHT', size1: '3/4"', size2: '3/4"', wall: '2', column: 'E', row: '12',  secondSize: false,}, 
    {type1: 'FHT', type2: 'Swivel Adapter', size1: '3/4"', size2: '1/2"', wall: '2', column: 'F', row: '12',  secondSize: true,}, 
    {type1: 'FHT', type2: 'Cap', size1: '3/4"', size2: '3/4"', wall: '2', column: 'C', row: '13',  secondSize: false,}, 
    {type1: 'FHT', type2: 'Ice Maker Elbow', size1: '3/4"', size2: '1/4"', wall: '2', column: 'D', row: '13',  secondSize: false,}, 
    {type1: 'FHT', type2: 'Swivel Adapter', size1: '3/4"', size2: '3/4"', wall: '2', column: 'E', row: '13',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Compression Elbow', size1: '7/8"', size2: '7/8"', wall: '2', column: 'C', row: '14',  secondSize: true,}, 
    {type1: 'FHT', type2: 'Coupling', size1: '3/4"', size2: '3/4"', wall: '2', column: 'D', row: '14',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Cap', size1: '5/8"', size2: '5/8"', wall: '3', column: 'A', row: '1',  secondSize: false,}, 
    {type1: 'Flare', type2: 'MIP Elbow', size1: '1/4"', size2: '1/8"', wall: '3', column: 'E', row: '1',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP Elbow', size1: '3/8"', size2: '1/4"', wall: '3', column: 'F', row: '1',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP Elbow', size1: '3/8"', size2: '3/8"', wall: '3', column: 'A', row: '2',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP Elbow', size1: '3/8"', size2: '1/2"', wall: '3', column: 'B', row: '2',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP Elbow', size1: '1/2"', size2: '3/8"', wall: '3', column: 'C', row: '2',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP Elbow', size1: '1/2"', size2: '1/2"', wall: '3', column: 'D', row: '2',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP Elbow', size1: '5/8"', size2: '1/2"', wall: '3', column: 'E', row: '2',  secondSize: true,}, 
    {type1: 'Flare', type2: 'Flare Elbow', size1: '3/8"', size2: '3/8"', wall: '3', column: 'F', row: '2',  secondSize: true,}, 
    {type1: 'Flare', type2: 'Flare Elbow', size1: '1/2"', size2: '1/2"', wall: '3', column: 'A', row: '3',  secondSize: true,}, 
    {type1: 'Flare', type2: 'FIP Elbow', size1: '3/8"', size2: '3/8"', wall: '3', column: 'B', row: '3',  secondSize: true,}, 
    {type1: 'Flare', type2: 'FIP Elbow', size1: '3/8"', size2: '1/2"', wall: '3', column: 'C', row: '3',  secondSize: true,}, 
    {type1: 'Flare', type2: 'FIP Elbow', size1: '1/2"', size2: '1/2"', wall: '3', column: 'D', row: '3',  secondSize: true,}, 
    {type1: 'Flare', type2: 'Short Nut', size1: '1/4"', size2: '1/4"', wall: '3', column: 'E', row: '3',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Short Nut', size1: '5/16"', size2: '5/16"', wall: '3', column: 'F', row: '3',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Short Nut', size1: '3/8"', size2: '3/8"', wall: '3', column: 'A', row: '4',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Short Nut', size1: '1/2"', size2: '1/2"', wall: '3', column: 'B', row: '4',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Short Nut', size1: '5/8"', size2: '5/8"', wall: '3', column: 'C', row: '4',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Forged Short Nut', size1: '3/8"', size2: '3/8"', wall: '3', column: 'D', row: '4',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Forged Short Nut', size1: '1/2"', size2: '1/2"', wall: '3', column: 'E', row: '4',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Forged Short Nut', size1: '5/8"', size2: '5/8"', wall: '3', column: 'F', row: '4',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Cap', size1: '1/4"', size2: '1/4"', wall: '3', column: 'A', row: '5',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Cap', size1: '3/8"', size2: '3/8"', wall: '3', column: 'B', row: '5',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Cap', size1: '1/2"', size2: '1/2"', wall: '3', column: 'C', row: '5',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Cap', size1: '5/8"', size2: '5/8"', wall: '3', column: 'D', row: '5',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Plug', size1: '1/4"', size2: '1/4"', wall: '3', column: 'E', row: '5',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Plug', size1: '3/8"', size2: '3/8"', wall: '3', column: 'F', row: '5',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Plug', size1: '1/2"', size2: '1/2"', wall: '3', column: 'A', row: '6',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Plug', size1: '5/8"', size2: '5/8"', wall: '3', column: 'B', row: '6',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Tee', size1: '1/4" x 1/4" x 1/4"', size2: '1/4" x 1/4" x 1/4"', wall: '3', column: 'C', row: '6',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Tee', size1: '3/8" x 3/8" x 3/8"', size2: '3/8" x 3/8" x 3/8"', wall: '3', column: 'D', row: '6',  secondSize: false,}, 
    {type1: 'Flare', type2: 'Tee', size1: '1/2" x 1/2" x 1/2"', size2: '1/2" x 1/2" x 1/2"', wall: '3', column: 'E', row: '6',  secondSize: false,}, 
    {type1: 'Flare', type2: 'MIP', size1: '1/4"', size2: '1/8"', wall: '3', column: 'F', row: '6',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP', size1: '1/4"', size2: '1/4"', wall: '3', column: 'A', row: '7',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP', size1: '5/16"', size2: '1/4"', wall: '3', column: 'B', row: '7',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP', size1: '3/8"', size2: '1/4"', wall: '3', column: 'C', row: '7',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP', size1: '3/8"', size2: '3/8"', wall: '3', column: 'D', row: '7',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP', size1: '3/8"', size2: '1/2"', wall: '3', column: 'E', row: '7',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP', size1: '3/8"', size2: '3/4"', wall: '3', column: 'F', row: '7',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP', size1: '1/2"', size2: '3/8"', wall: '3', column: 'A', row: '8',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP', size1: '1/2"', size2: '1/2"', wall: '3', column: 'B', row: '8',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP', size1: '1/2"', size2: '3/4"', wall: '3', column: 'C', row: '8',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP', size1: '5/8"', size2: '1/2"', wall: '3', column: 'D', row: '8',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP', size1: '5/8"', size2: '3/4"', wall: '3', column: 'E', row: '8',  secondSize: true,}, 
    {type1: 'Flare', type2: 'Flare', size1: '1/4"', size2: '1/4"', wall: '3', column: 'F', row: '8',  secondSize: true,}, 
    {type1: 'Flare', type2: 'Flare', size1: '3/8"', size2: '1/4"', wall: '3', column: 'A', row: '9',  secondSize: true,}, 
    {type1: 'Flare', type2: 'Flare', size1: '3/8"', size2: '3/8"', wall: '3', column: 'B', row: '9',  secondSize: true,}, 
    {type1: 'Flare', type2: 'Flare', size1: '1/2"', size2: '1/2"', wall: '3', column: 'C', row: '9',  secondSize: true,}, 
    {type1: 'Flare', type2: 'Flare', size1: '1/2"', size2: '3/8"', wall: '3', column: 'D', row: '9',  secondSize: true,}, 
    {type1: 'Flare', type2: 'Flare', size1: '5/8"', size2: '1/2"', wall: '3', column: 'E', row: '9',  secondSize: true,}, 
    {type1: 'Flare', type2: 'Flare', size1: '5/8"', size2: '5/8"', wall: '3', column: 'F', row: '9',  secondSize: true,}, 
    {type1: 'Flare', type2: 'FIP', size1: '1/4"', size2: '1/8"', wall: '3', column: 'A', row: '10',  secondSize: true,}, 
    {type1: 'Flare', type2: 'FIP', size1: '1/4"', size2: '1/4"', wall: '3', column: 'B', row: '10',  secondSize: true,}, 
    {type1: 'Flare', type2: 'FIP', size1: '3/8"', size2: '1/4"', wall: '3', column: 'C', row: '10',  secondSize: true,}, 
    {type1: 'Flare', type2: 'FIP', size1: '3/8"', size2: '3/8"', wall: '3', column: 'D', row: '10',  secondSize: true,}, 
    {type1: 'Flare', type2: 'FIP', size1: '3/8"', size2: '1/2"', wall: '3', column: 'E', row: '10',  secondSize: true,}, 
    {type1: 'Flare', type2: 'FIP', size1: '3/8"', size2: '3/4"', wall: '3', column: 'F', row: '10',  secondSize: true,}, 
    {type1: 'Flare', type2: 'FIP', size1: '1/2"', size2: '3/8"', wall: '3', column: 'A', row: '11',  secondSize: true,}, 
    {type1: 'Flare', type2: 'FIP', size1: '1/2"', size2: '1/2"', wall: '3', column: 'B', row: '11',  secondSize: true,}, 
    {type1: 'Flare', type2: 'FIP', size1: '1/2"', size2: '3/4"', wall: '3', column: 'C', row: '11',  secondSize: true,}, 
    {type1: 'Flare', type2: 'FIP', size1: '5/8"', size2: '1/2"', wall: '3', column: 'D', row: '11',  secondSize: true,}, 
    {type1: 'Flare', type2: 'FIP', size1: '5/8"', size2: '3/4"', wall: '3', column: 'E', row: '11',  secondSize: true,}, 
    {type1: 'Flare', type2: 'FIP', size1: '3/4"', size2: '1/2"', wall: '3', column: 'F', row: '11',  secondSize: true,}, 
    {type1: 'Flare', type2: 'Swivel Union', size1: '3/8"', size2: '3/8"', wall: '3', column: 'A', row: '12',  secondSize: true,}, 
    {type1: 'Flare', type2: 'Swivel Union', size1: '1/2"', size2: '3/8"', wall: '3', column: 'C', row: '12',  secondSize: true,}, 
    {type1: 'Flare', type2: 'Swivel Union', size1: '5/8"', size2: '5/8"', wall: '3', column: 'D', row: '12',  secondSize: true,}, 
    {type1: 'Flare', type2: 'Swivel Union', size1: '5/8"', size2: '1/2"', wall: '3', column: 'E', row: '12',  secondSize: true,}, 
    {type1: 'Flare', type2: 'Swivel Union', size1: '1/4"', size2: '1/4"', wall: '3', column: 'F', row: '12',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP', size1: '15/16"', size2: '1/2"', wall: '3', column: 'A', row: '13',  secondSize: true,}, 
    {type1: 'Flare', type2: 'MIP', size1: '15/16"', size2: '3/4"', wall: '3', column: 'C', row: '13',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Sleeve', size1: '1/8"', size2: '1/8"', wall: '4', column: 'A', row: '1',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Sleeve', size1: '3/16"', size2: '3/16"', wall: '4', column: 'B', row: '1',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Sleeve', size1: '1/4"', size2: '1/4"', wall: '4', column: 'C', row: '1',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Sleeve', size1: '5/16"', size2: '5/16"', wall: '4', column: 'D', row: '1',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Sleeve', size1: '3/8"', size2: '3/8"', wall: '4', column: 'E', row: '1',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Sleeve', size1: '1/2"', size2: '1/2"', wall: '4', column: 'F', row: '1',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Sleeve', size1: '5/8"', size2: '5/8"', wall: '4', column: 'A', row: '2',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Sleeve', size1: '7/8"', size2: '7/8"', wall: '4', column: 'B', row: '2',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Nut', size1: '1/8"', size2: '1/8"', wall: '4', column: 'C', row: '2',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Nut', size1: '3/16"', size2: '3/16"', wall: '4', column: 'D', row: '2',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Nut', size1: '1/4"', size2: '1/4"', wall: '4', column: 'E', row: '2',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Nut', size1: '5/16"', size2: '5/16"', wall: '4', column: 'F', row: '2',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Nut', size1: '3/8"', size2: '3/8"', wall: '4', column: 'A', row: '3',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Nut', size1: '1/2"', size2: '1/2"', wall: '4', column: 'B', row: '3',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Nut', size1: '5/8"', size2: '5/8"', wall: '4', column: 'C', row: '3',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Nut', size1: '7/8"', size2: '7/8"', wall: '4', column: 'D', row: '3',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Delrin Sleeve', size1: '1/4"', size2: '1/4"', wall: '4', column: 'E', row: '3',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Delrin Sleeve', size1: '5/16"', size2: '5/16"', wall: '4', column: 'F', row: '3',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Delrin Sleeve', size1: '3/8"', size2: '3/8"', wall: '4', column: 'A', row: '4',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Delrin Sleeve', size1: '1/2"', size2: '1/2"', wall: '4', column: 'B', row: '4',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Insert', size1: '1/4"', size2: '1/4"', wall: '4', column: 'C', row: '4',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Insert', size1: '5/16"', size2: '5/16"', wall: '4', column: 'D', row: '4',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Insert', size1: '3/8"', size2: '3/8"', wall: '4', column: 'E', row: '4',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Insert', size1: '1/2"', size2: '1/2"', wall: '4', column: 'F', row: '4',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Compression', size1: '1/8"', size2: '1/8"', wall: '4', column: 'A', row: '5',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Compression', size1: '3/16"', size2: '3/16"', wall: '4', column: 'B', row: '5',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Compression', size1: '1/4"', size2: '1/4"', wall: '4', column: 'C', row: '5',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Compression', size1: '5/16"', size2: '5/16"', wall: '4', column: 'D', row: '5',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Compression', size1: '3/8"', size2: '1/4"', wall: '4', column: 'E', row: '5',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Compression', size1: '3/8"', size2: '3/8"', wall: '4', column: 'F', row: '5',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Compression', size1: '1/2"', size2: '3/8"', wall: '4', column: 'A', row: '6',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Compression', size1: '1/2"', size2: '1/2"', wall: '4', column: 'B', row: '6',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Compression', size1: '5/8"', size2: '1/2"', wall: '4', column: 'C', row: '6',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP', size1: '5/16"', size2: '1/8"', wall: '4', column: 'D', row: '6',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Compression', size1: '5/8"', size2: '5/8"', wall: '4', column: 'E', row: '6',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Compression', size1: '7/8"', size2: '7/8"', wall: '4', column: 'F', row: '6',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Tee', size1: '1/4" x 1/4" x 1/4"', size2: '1/4" x 1/4" x 1/4"', wall: '4', column: 'A', row: '7',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Tee', size1: '5/16" x 5/16" x 5/16"', size2: '5/16" x 5/16" x 5/16"', wall: '4', column: 'B', row: '7',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Tee', size1: '3/8" x 3/8" x 1/4"', size2: '3/8" x 3/8" x 1/4"', wall: '4', column: 'C', row: '7',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Tee', size1: '3/8" x 3/8" x 3/8"', size2: '3/8" x 3/8" x 3/8"', wall: '4', column: 'D', row: '7',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Tee', size1: '1/2" x 1/2" x 1/2"', size2: '1/2" x 1/2" x 1/2"', wall: '4', column: 'E', row: '7',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Tee', size1: '5/8" x 5/8" x 5/8"', size2: '5/8" x 5/8" x 5/8"', wall: '4', column: 'F', row: '7',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Compression Elbow', size1: '1/4"', size2: '1/4"', wall: '4', column: 'A', row: '8',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Compression Elbow', size1: '3/8"', size2: '3/8"', wall: '4', column: 'B', row: '8',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Compression Elbow', size1: '1/2"', size2: '1/2"', wall: '4', column: 'C', row: '8',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Compression Elbow', size1: '5/8"', size2: '5/8"', wall: '4', column: 'D', row: '8',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Sweat', size1: '3/8"', size2: '1/2"', wall: '4', column: 'E', row: '8',  secondSize: true,}, 
    {type1: 'Compression', type2: 'FIP', size1: '1/4"', size2: '1/8"', wall: '4', column: 'F', row: '8',  secondSize: true,}, 
    {type1: 'Compression', type2: 'FIP', size1: '1/4"', size2: '1/4"', wall: '4', column: 'A', row: '9',  secondSize: true,}, 
    {type1: 'Compression', type2: 'FIP', size1: '1/4"', size2: '1/2"', wall: '4', column: 'B', row: '9',  secondSize: true,}, 
    {type1: 'Compression', type2: 'FIP', size1: '3/8"', size2: '1/4"', wall: '4', column: 'C', row: '9',  secondSize: true,}, 
    {type1: 'Compression', type2: 'FIP', size1: '3/8"', size2: '3/8"', wall: '4', column: 'D', row: '9',  secondSize: true,}, 
    {type1: 'Compression', type2: 'FIP', size1: '3/8"', size2: '1/2"', wall: '4', column: 'E', row: '9',  secondSize: true,}, 
    {type1: 'Compression', type2: 'FIP', size1: '1/2"', size2: '1/2"', wall: '4', column: 'F', row: '9',  secondSize: true,}, 
    {type1: 'Compression', type2: 'FIP', size1: '5/8"', size2: '1/2"', wall: '4', column: 'A', row: '10',  secondSize: true,}, 
    {type1: 'Compression', type2: 'FIP', size1: '7/8"', size2: '3/4"', wall: '4', column: 'B', row: '10',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP', size1: '1/8"', size2: '1/8"', wall: '4', column: 'C', row: '10',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP', size1: '3/16"', size2: '1/8"', wall: '4', column: 'D', row: '10',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP', size1: '1/4"', size2: '1/8"', wall: '4', column: 'E', row: '10',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP', size1: '1/4"', size2: '1/4"', wall: '4', column: 'F', row: '10',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP', size1: '5/16"', size2: '1/4"', wall: '4', column: 'B', row: '11',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP', size1: '3/8"', size2: '1/8"', wall: '4', column: 'C', row: '11',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP', size1: '3/8"', size2: '1/4"', wall: '4', column: 'D', row: '11',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP', size1: '3/8"', size2: '3/8"', wall: '4', column: 'E', row: '11',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP', size1: '3/8"', size2: '1/2"', wall: '4', column: 'F', row: '11',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP', size1: '1/2"', size2: '1/4"', wall: '4', column: 'A', row: '12',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP', size1: '1/2"', size2: '3/8"', wall: '4', column: 'B', row: '12',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP', size1: '1/2"', size2: '1/2"', wall: '4', column: 'C', row: '12',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP', size1: '5/8"', size2: '1/2"', wall: '4', column: 'D', row: '12',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP', size1: '5/8"', size2: '3/4"', wall: '4', column: 'E', row: '12',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP', size1: '7/8"', size2: '3/4"', wall: '4', column: 'F', row: '12',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP Elbow', size1: '1/4"', size2: '1/8"', wall: '4', column: 'A', row: '13',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP Elbow', size1: '1/4"', size2: '1/4"', wall: '4', column: 'B', row: '13',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP Elbow', size1: '3/8"', size2: '1/4"', wall: '4', column: 'C', row: '13',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP Elbow', size1: '3/8"', size2: '3/8"', wall: '4', column: 'D', row: '13',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP Elbow', size1: '3/8"', size2: '1/2"', wall: '4', column: 'E', row: '13',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP Elbow', size1: '1/2"', size2: '3/8"', wall: '4', column: 'F', row: '13',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP Elbow', size1: '1/2"', size2: '1/2"', wall: '4', column: 'A', row: '14',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP Elbow', size1: '5/8"', size2: '1/2"', wall: '4', column: 'B', row: '14',  secondSize: true,}, 
    {type1: 'Compression', type2: 'MIP Elbow', size1: '7/8"', size2: '7/8"', wall: '4', column: 'C', row: '14',  secondSize: true,}, 
    {type1: 'Compression', type2: 'Cap', size1: '1/4"', size2: '1/4"', wall: '4', column: 'D', row: '14',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Cap', size1: '3/8"', size2: '3/8"', wall: '4', column: 'E', row: '14',  secondSize: false,}, 
    {type1: 'Compression', type2: 'Cap', size1: '1/2"', size2: '1/2"', wall: '4', column: 'F', row: '14',  secondSize: false,},
];

export default MasterData;